blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/loupewire/loupewire-support/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🛍️ Chrome Web Store
    url: https://chromewebstore.google.com/detail/dkoclbklglebhboiodckkicoajbcmbjd
    about: Install and rate on Chrome Web Store
  - name: 🛍️ Microsoft Edge Add-ons
    url: https://microsoftedge.microsoft.com/addons/detail/fobjeeglpkfdalljagicbgelbdmhlhgf
    about: Install and rate on Edge Add-ons
  - name: 📖 Privacy & Terms
    url: https://loupewire.com/privacy-policy/
    about: How Loupewire handles your data
